project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
      - text: "Home"
        file: about.qmd
      - text: Blog
        file: blog.qmd
      - text: Poems
        file: poems.qmd
  repo-url: https://github.com/bpffjl/bpffjl-website
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
